// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC65OYUHDDgz9RBDtlePPmitJ9Z8d55qsE',
    appId: '1:93716660341:web:1c0a5bc01f195f4655f83c',
    messagingSenderId: '93716660341',
    projectId: 'blocapp-58332',
    authDomain: 'blocapp-58332.firebaseapp.com',
    storageBucket: 'blocapp-58332.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVJsL86aQ0WFRzqSnWxwW13X6TJl0HqbY',
    appId: '1:93716660341:android:ccabda2d033e0dd055f83c',
    messagingSenderId: '93716660341',
    projectId: 'blocapp-58332',
    storageBucket: 'blocapp-58332.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhfNoJwdOwKV59SmX-3RrtPt3SqBqPX_g',
    appId: '1:93716660341:ios:445b3c863ea1ed6d55f83c',
    messagingSenderId: '93716660341',
    projectId: 'blocapp-58332',
    storageBucket: 'blocapp-58332.appspot.com',
    iosClientId: '93716660341-hd5ijgdag6sdt4js2dc1of2g3akl5q7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhfNoJwdOwKV59SmX-3RrtPt3SqBqPX_g',
    appId: '1:93716660341:ios:445b3c863ea1ed6d55f83c',
    messagingSenderId: '93716660341',
    projectId: 'blocapp-58332',
    storageBucket: 'blocapp-58332.appspot.com',
    iosClientId: '93716660341-hd5ijgdag6sdt4js2dc1of2g3akl5q7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocApp',
  );
}
